# GitLab CI/CD configuration file for ngen repository
stages:
  - build
  - unit_test
  - sonarqube
  - deploy
  - ver_test

build-job:
  stage: build
#  variables:
#    GIT_SUBMODULE_STRATEGY: recursive
#    GIT_SUBMODULE_FORCE_HTTPS: "true"
#    GIT_TRACE: "true"
#    GIT_SUBMODULE_DEPTH: 1
  before_script:
    - git config --global url."https://oauth2:${GITLAB_TOKEN}@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - echo "Building NGEN..."
    - sudo chmod 777 ./scripts/submodule_update.sh ./scripts/build.sh
    - ./scripts/submodule_update.sh
    - cd ..
    - tar -czf ngen.tar.gz ngen
    - cd ngen
    - ./scripts/build.sh
    - echo "Build complete."

unit-test-job:
  stage: unit_test
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Running unit tests..."
    - source /opt/ngen/python/bin/activate
    - ./cmake_build/test/test_unit
    - ./cmake_build/test/test_all
    - ./cmake_build/test/test_bmi_c
    - ./cmake_build/test/test_bmi_fortran
    - echo "Unit tests complete"

sonarqube-job:
  stage: sonarqube
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - echo "Running Sonarqube scan..."
    - ~/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner

deploy-job:
  stage: deploy
  environment: test # NGEN-TEST-COPY
  before_script:
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Deploying NGEN..."
    - scp ../ngen.tar.gz christina.osumi@10.105.133.122:~/ngen-app
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY christina.osumi@10.105.133.122 "
        cd ~/ngen-app &&
        rm -rf ngen &&
        tar -xzf ngen.tar.gz &&
        rm ngen.tar.gz &&
        cd ngen &&
        ./scripts/build.sh"
    - echo "NGEN deployed to NGEN-Test"

ver-test-job:
  stage: ver_test
  environment: test # NGEN-TEST-COPY
  before_script:
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Running verification tests..."
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY christina.osumi@10.105.133.122 "
        cd ~/ngen-app" # TODO add verification test example to common test repo
    - echo "Verification tests complete"
