# GitLab CI/CD configuration file for ngen repository
variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build
  - unit_test
  - sonarqube
  - deploy_test
  - ver_test
  - deploy_oe

build-job:
  stage: build
  script:
    - echo "Building NGEN..."
    - ./scripts/submodule_update.sh
    - sudo chmod 666 /var/run/docker.sock
    - docker rm -f ngen-build-container || true
    - docker run --name ngen-build-container -v .:/ngen-app/ngen -e GITLAB_TOKEN=$GITLAB_TOKEN rockylinux:8 bash -c "cd /ngen-app/ngen &&
        ./scripts/build.sh"
    - sudo chown -R `whoami` .
    - tar -czf ../ngen.tar.gz .
    - echo "Build complete." 

unit-test-job:
  stage: unit_test
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Running unit tests..."
    - docker start ngen-build-container
    - docker exec ngen-build-container bash -c "
        source /opt/ngen-python/bin/activate &&
        cd /ngen-app/ngen &&
        ./cmake_build/test/test_unit &&
        ./cmake_build/test/test_all &&
        ./cmake_build/test/test_bmi_c &&
        ./cmake_build/test/test_bmi_fortran &&
        ./cmake_build_no_mpi/test/test_unit &&
        ./cmake_build_no_mpi/test/test_all &&
        ./cmake_build_no_mpi/test/test_bmi_c &&
        ./cmake_build_no_mpi/test/test_bmi_fortran &&
        ./cmake_build_no_mpi_netcdf/test/test_unit &&
        ./cmake_build_no_mpi_netcdf/test/test_all &&
        ./cmake_build_no_mpi_netcdf/test/test_bmi_c &&
        ./cmake_build_no_mpi_netcdf/test/test_bmi_fortran &&
        ./cmake_build_no_netcdf/test/test_unit &&
        ./cmake_build_no_netcdf/test/test_all &&
        ./cmake_build_no_netcdf/test/test_bmi_c &&
        ./cmake_build_no_netcdf/test/test_bmi_fortran &&
        ./cmake_build_no_sqlite/test/test_unit &&
        ./cmake_build_no_sqlite/test/test_all &&
        ./cmake_build_no_sqlite/test/test_bmi_c &&
        ./cmake_build_no_sqlite/test/test_bmi_fortran"
    - echo "Unit tests complete"
  allow_failure: true

sonarqube-job:
  stage: sonarqube
  variables:
    GIT_STRATEGY: none
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - echo "Running Sonarqube scan..."
    - node -v
    - ~/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner -X
#      -Dsonar.projectKey=my-project-${CI_COMMIT_BRANCH}
  allow_failure: true

deploy-test-job:
  stage: deploy_test
  variables:
    GIT_STRATEGY: none
  environment: test # NGEN_TEST_ENV
  before_script:
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Deploying NGEN to TEST..."
    - scp ../ngen.tar.gz christina.osumi@10.203.109.228:~/ngen-app
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY christina.osumi@10.203.109.228 "
        cd ~/ngen-app &&
        rm -rf ngen &&
        mkdir -p ngen &&
        tar -xzf ngen.tar.gz -C ngen &&
        rm ngen.tar.gz"
    - echo "NGEN deployed to TEST"
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_MERGE_REQUEST_STATE == "merged"'

ver-test-job:
  stage: ver_test
  variables:
    GIT_STRATEGY: none
  before_script:
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Running verification tests..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - git config --global url."https://oauth2:${GITLAB_TOKEN}@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"
    - git clone https://gitlab.sh.nextgenwaterprediction.com/NGWPC/ngwpc-test
    - cd ngwpc-test/NGEN
    - docker build -t $CONTAINER_TEST_IMAGE -f docker/Dockerfile.selenium .
    - docker push $CONTAINER_TEST_IMAGE
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY christina.osumi@10.203.109.228 "
       sudo chmod 666 /var/run/docker.sock &&
       docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
       docker pull $CONTAINER_TEST_IMAGE &&
       docker run $CONTAINER_TEST_IMAGE"
    - echo "Verification tests complete"
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_MERGE_REQUEST_STATE == "merged"'

deploy-oe-job:
  stage: deploy_oe
  when: manual
  variables:
    GIT_STRATEGY: none
  environment: oe # NGEN-HYDRO-OE
  before_script:
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Deploying NGEN to OE..."
    - scp ../ngen.tar.gz christina.osumi@10.203.104.196:~/ngen-app
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY christina.osumi@10.203.104.196 "
        cd ~/ngen-app &&
        rm -rf ngen &&
        mkdir -p ngen &&
        tar -xzf ngen.tar.gz -C ngen &&
        rm ngen.tar.gz"
    - echo "NGEN deployed to OE"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_MERGE_REQUEST_STATE == "merged"'