NGen: Logger Class Reference
Logger Class Reference
Logger Class Used to Output Details of Current Application Flow.
#include <Logger.hpp>
Public Member Functions
Logger ()
~Logger ()=default
bool IsLoggingEnabled (void)
LogLevel GetLogLevel (void)
void SetLogPreferences (LogLevel level=LogLevel::INFO)
Configure Logger Preferences and open log file.
Static Public Member Functions
static void Log (std::string message, LogLevel messageLevel=LogLevel::INFO)
Log given message with defined parameters and generate message to pass on Console or File.
static void Log (LogLevel messageLevel, const char *message,...)
static void Log (LogLevel messageLevel, std::string message)
Log given message with defined parameters and generate message to pass on Console or File.
static __always_inline void logMsgAndThrowError (const std::string &message)
Private Member Functions
std::string CreateDateString (void)
bool CreateDirectory (const std::string &path)
Create the directory checking both the call to execute the command and the result of the command.
bool DirectoryExists (const std::string &path)
std::string ExtractFirstNDirs (const std::string &path, int numDirs)
bool FileExists (const std::string &path)
bool FindAndOpenLogConfigFile (std::string path, std::ifstream &configFileStream)
std::string GetLogFilePath (void)
std::string GetParentDirName (const std::string &path)
bool JsonFileValid (std::ifstream &jsonFile)
bool LogFileReady (void)
Open log file and return open status.
bool ParseLoggerConfigFile (std::ifstream &jsonFile)
void ReadConfigFile (std::string searchPath)
void SetupLogFile (void)
void ManageLoggingEnvVars (bool set=true)
Static Private Member Functions
static std::string ConvertLogLevelToString (LogLevel level)
static LogLevel ConvertStringToLogLevel (const std::string &logLevel)
Convert String Representation of Log Level to LogLevel Type.
static std::string CreateTimestamp (bool appendMS=true, bool iso=true)
static std::string ToUpper (const std::string &str)
static std::string TrimString (const std::string &str)
static Logger * GetLogger ()
Private Attributes
bool loggerInitialized = false
bool loggingEnabled = true
std::fstream logFile
std::string logFileDir = ""
std::string logFilePath = ""
LogLevel logLevel = LogLevel::INFO
std::string moduleName = ""
std::string ngenResultsDir = ""
bool openedOnce = false
std::unordered_map< std::string, LogLevel > moduleLogLevels
Detailed Description
Logger Class Used to Output Details of Current Application Flow.
Constructor & Destructor Documentation
Logger()
Logger::Logger ()
Referenced by GetLogger().
~Logger()
Logger::~Logger () default
Member Function Documentation
ConvertLogLevelToString()
std::string Logger::ConvertLogLevelToString (LogLevel level) static private
Referenced by Log(), ManageLoggingEnvVars(), ParseLoggerConfigFile(), and SetLogPreferences().
ConvertStringToLogLevel()
LogLevel Logger::ConvertStringToLogLevel (const std::string & levelStr) static private
Convert String Representation of Log Level to LogLevel Type.
Parameters
levelStr : String log level
Returns
LogLevel
References TrimString().
Referenced by ParseLoggerConfigFile().
CreateDateString()
std::string Logger::CreateDateString (void) private
Referenced by SetupLogFile().
CreateDirectory()
bool Logger::CreateDirectory (const std::string & path) private
Create the directory checking both the call to execute the command and the result of the command.
References DirectoryExists().
Referenced by SetupLogFile().
CreateTimestamp()
std::string Logger::CreateTimestamp (bool appendMS = true, bool iso = true) static private
Referenced by Log(), and SetupLogFile().
DirectoryExists()
bool Logger::DirectoryExists (const std::string & path) private
Referenced by CreateDirectory(), and SetupLogFile().
ExtractFirstNDirs()
std::string Logger::ExtractFirstNDirs (const std::string & path, int numDirs) private
FileExists()
bool Logger::FileExists (const std::string & path) private
Referenced by FindAndOpenLogConfigFile().
FindAndOpenLogConfigFile()
bool Logger::FindAndOpenLogConfigFile (std::string path, std::ifstream & configFileStream) private
References FileExists(), and GetParentDirName().
Referenced by ReadConfigFile().
GetLogFilePath()
std::string Logger::GetLogFilePath (void) private
References logFilePath.
GetLogger()
Logger * Logger::GetLogger () static private
References Logger(), and SetLogPreferences().
Referenced by Log().
GetLogLevel()
LogLevel Logger::GetLogLevel (void)
References logLevel.
GetParentDirName()
std::string Logger::GetParentDirName (const std::string & path) private
Referenced by FindAndOpenLogConfigFile().
IsLoggingEnabled()
bool Logger::IsLoggingEnabled (void)
References loggingEnabled.
JsonFileValid()
bool Logger::JsonFileValid (std::ifstream & jsonFile) private
Referenced by ParseLoggerConfigFile().
Log() [1/3]
void Logger::Log (LogLevel messageLevel, const char * message, ...) static
References Log().
Log() [2/3]
void Logger::Log (LogLevel messageLevel, std::string message) static
Log given message with defined parameters and generate message to pass on Console or File.
Parameters
message Log Message
messageLevel Log Level, LogLevel::INFO by default
References Log().
Log() [3/3]
void Logger::Log (std::string message, LogLevel messageLevel = LogLevel::INFO) static
Log given message with defined parameters and generate message to pass on Console or File.
Parameters
message Log Message
messageLevel Log Level, LogLevel::INFO by default
References ConvertLogLevelToString(), CreateTimestamp(), GetLogger(), logFile, LogFileReady(), loggingEnabled, logLevel, and moduleName.
Referenced by realization::Bmi_Module_Formulation::get_response(), Log(), Log(), logMsgAndThrowError(), SetLogPreferences(), and SetupLogFile().
LogFileReady()
bool Logger::LogFileReady (void) private
Open log file and return open status.
If already open, ensure the write pointer is at the end of the file.
return bool true if open and good, false otherwise
References logFile, logFilePath, and openedOnce.
Referenced by Log().
logMsgAndThrowError()
static __always_inline void Logger::logMsgAndThrowError (const std::string & message) inline static
References Log().
Referenced by models::bmi::Bmi_Adapter::Bmi_Adapter(), data_access::detail::assert_forcings_engine_requirements(), ngen::geopackage::build_geometry(), realization::Bmi_C_Formulation::construct_model(), realization::Bmi_Cpp_Formulation::construct_model(), realization::Bmi_Multi_Formulation::create_multi_formulation(), models::bmi::AbstractCLibBmiAdapter::dynamic_library_load(), models::bmi::AbstractCLibBmiAdapter::dynamic_load_symbol(), realization::Bmi_Multi_Formulation::get_response(), realization::Bmi_C_Formulation::get_var_value_as_double(), realization::Bmi_Cpp_Formulation::get_var_value_as_double(), models::bmi::Bmi_C_Adapter::GetComponentName(), models::bmi::Bmi_C_Adapter::GetCurrentTime(), models::bmi::Bmi_C_Adapter::GetEndTime(), models::bmi::Bmi_C_Adapter::GetGridEdgeCount(), models::bmi::Bmi_C_Adapter::GetGridEdgeNodes(), models::bmi::Bmi_C_Adapter::GetGridFaceCount(), models::bmi::Bmi_C_Adapter::GetGridFaceEdges(), models::bmi::Bmi_C_Adapter::GetGridFaceNodes(), models::bmi::Bmi_C_Adapter::GetGridNodeCount(), models::bmi::Bmi_C_Adapter::GetGridNodesPerFace(), models::bmi::Bmi_C_Adapter::GetGridOrigin(), models::bmi::Bmi_C_Adapter::GetGridRank(), models::bmi::Bmi_C_Adapter::GetGridShape(), models::bmi::Bmi_C_Adapter::GetGridSize(), models::bmi::Bmi_C_Adapter::GetGridSpacing(), models::bmi::Bmi_C_Adapter::GetGridType(), models::bmi::Bmi_C_Adapter::GetGridX(), models::bmi::Bmi_C_Adapter::GetGridY(), models::bmi::Bmi_C_Adapter::GetGridZ(), models::bmi::Bmi_C_Adapter::GetStartTime(), models::bmi::Bmi_C_Adapter::GetTimeUnits(), models::bmi::Bmi_C_Adapter::GetVarGrid(), models::bmi::Bmi_C_Adapter::GetVarItemsize(), models::bmi::Bmi_C_Adapter::GetVarLocation(), models::bmi::Bmi_C_Adapter::GetVarNbytes(), models::bmi::Bmi_C_Adapter::GetVarType(), models::bmi::Bmi_C_Adapter::GetVarUnits(), models::bmi::Bmi_Adapter::Initialize(), models::bmi::Bmi_Adapter::Initialize(), models::bmi::Bmi_C_Adapter::inner_get_variable_names(), ngen::geopackage::wkb::read(), ngen::geopackage::throw_if_not_type(), ngen::mdframe::to_csv(), and ngen::mdframe::to_netcdf().
ManageLoggingEnvVars()
void Logger::ManageLoggingEnvVars (bool set = true) private
References ConvertLogLevelToString(), loggingEnabled, logLevel, and moduleLogLevels.
Referenced by ReadConfigFile().
ParseLoggerConfigFile()
bool Logger::ParseLoggerConfigFile (std::ifstream & jsonFile) private
References ConvertLogLevelToString(), ConvertStringToLogLevel(), JsonFileValid(), loggingEnabled, moduleLogLevels, ToUpper(), and TrimString().
Referenced by ReadConfigFile().
ReadConfigFile()
void Logger::ReadConfigFile (std::string searchPath) private
References FindAndOpenLogConfigFile(), loggingEnabled, ManageLoggingEnvVars(), moduleLogLevels, and ParseLoggerConfigFile().
Referenced by SetLogPreferences().
SetLogPreferences()
void Logger::SetLogPreferences (LogLevel level = LogLevel::INFO)
Configure Logger Preferences and open log file.
Parameters
level LogLevel::WARNING by Default
Returns
void
References ConvertLogLevelToString(), Log(), logFileDir, logFilePath, loggerInitialized, loggingEnabled, logLevel, moduleName, ngenResultsDir, ReadConfigFile(), and SetupLogFile().
Referenced by GetLogger().
SetupLogFile()
void Logger::SetupLogFile (void) private
References CreateDateString(), CreateDirectory(), CreateTimestamp(), DirectoryExists(), Log(), logFile, logFileDir, logFilePath, logLevel, ngenResultsDir, and openedOnce.
Referenced by SetLogPreferences().
ToUpper()
std::string Logger::ToUpper (const std::string & str) static private
Referenced by ParseLoggerConfigFile().
TrimString()
std::string Logger::TrimString (const std::string & str) static private
Referenced by ConvertStringToLogLevel(), and ParseLoggerConfigFile().
Member Data Documentation
logFile
std::fstream Logger::logFile private
Referenced by Log(), LogFileReady(), and SetupLogFile().
logFileDir
std::string Logger::logFileDir = "" private
Referenced by SetLogPreferences(), and SetupLogFile().
logFilePath
std::string Logger::logFilePath = "" private
Referenced by GetLogFilePath(), LogFileReady(), SetLogPreferences(), and SetupLogFile().
loggerInitialized
bool Logger::loggerInitialized = false private
Referenced by SetLogPreferences().
loggingEnabled
bool Logger::loggingEnabled = true private
Referenced by IsLoggingEnabled(), Log(), ManageLoggingEnvVars(), ParseLoggerConfigFile(), ReadConfigFile(), and SetLogPreferences().
logLevel
LogLevel Logger::logLevel = LogLevel::INFO private
Referenced by GetLogLevel(), Log(), ManageLoggingEnvVars(), SetLogPreferences(), and SetupLogFile().
moduleLogLevels
std::unordered_map<std::string, LogLevel> Logger::moduleLogLevels private
Referenced by ManageLoggingEnvVars(), ParseLoggerConfigFile(), and ReadConfigFile().
moduleName
std::string Logger::moduleName = "" private
Referenced by Log(), and SetLogPreferences().
ngenResultsDir
std::string Logger::ngenResultsDir = "" private
Referenced by SetLogPreferences(), and SetupLogFile().
openedOnce
bool Logger::openedOnce = false private
Referenced by LogFileReady(), and SetupLogFile().
The documentation for this class was generated from the following files:
include/utilities/Logger.hpp
src/utilities/logging/Logger.cpp